kumuluzee:
  name: minimal-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8282
    http:
      port: 8282
  datasources:
  - jndi-name: jdbc/minimal
    connection-url: jdbc:postgresql://192.168.99.100:5432/minimaldb
    username: postgres
    password: postgres
    max-pool-size: 20